config/routes.rb
TheBirdsuit::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  
  resources :artists, :only => [:index, :show] do
    member do
      get 'video'
    end
    resources :releases, :only => [:show]
  end
  resources :posts, :only => [:index, :show]
  match 'blog' => 'posts#index', :as => :blog
  match 'promo' => 'pages#promo', :as => :promo
  match 'story' => 'pages#story', :as => :story
  match 'contact' => 'pages#contact', :as => :contact

end

app/models/artist.rb
# == Schema Information
# Schema version: 20110421202631
#
# Table name: artists
#
#  id                        :integer         not null, primary key
#  name                      :string(255)
#  bio_pic_url               :string(255)
#  bio_pic_hover_url         :string(255)
#  biography_text            :text
#  twitter_id                :string(255)
#  roster_pic_url            :string(255)
#  roster_pic_hover_url      :string(255)
#  bio_video_url             :string(255)
#  bio_video_id              :string(255)
#  bio_video_type            :string(255)
#  created_at                :datetime
#  updated_at                :datetime
#  cached_slug               :string(255)
#  bio_video_img_url         :string(255)
#  bio_video_img_hover_url   :string(255)
#  artist_home_img_url       :string(255)
#  artist_home_img_hover_url :string(255)
#  sort_id                   :integer
#

class Artist < ActiveRecord::Base
  has_many :releases
  has_friendly_id :name, :use_slug => true

  attr_accessible :name, :bio_pic_url, :bio_pic_hover_url, :biography_text, :twitter_id, :roster_pic_url, :roster_pic_hover_url, :bio_video_url, :cached_slug, :bio_video_img_url, :bio_video_img_hover_url, :sort_id
  
  validates_presence_of :name, :bio_pic_url, :bio_pic_hover_url, :biography_text, :twitter_id, :roster_pic_url, :roster_pic_hover_url, :bio_video_url, :bio_video_img_url, :bio_video_img_hover_url
  
  default_scope order('sort_id ASC')
  
    before_validation :get_video_info
  
  def get_video_info
    self.bio_video_id = video[:id]
    self.bio_video_type = video[:type]
  end
  
  def video
    begin
      #YouTube
      if bio_video_url.match(/http:\/\/www\.youtube\.com\/watch\?v=([a-z0-9_\/-]+).*/i)
        {:id => $1, :type => 'youtube'}
      #----- Vimeo ------ #      
      elsif bio_video_url.match(/http:\/\/vimeo\.com\/([a-z0-9]+).*/i)
        {:id => $1, :type => 'vimeo'}
      elsif bio_video_url.match(/http:\/\/www\.vimeo\.com\/([a-z0-9]+).*/i) 
        {:id => $1, :type => 'vimeo'}
      else
        {:id => nil, :type => 'website'}
      end
    rescue Exception
      return {:id => nil, :type => nil}
    end
  end
  
  
end

app/controllers/artists_controller.rb
class ArtistsController < InheritedResources::Base
  actions :index, :show
  respond_to :html

  def video
    @artist = Artist.find(params[:id])
  end

end

app/views/artists/_scrollbar.html.erb
<%= javascript_include_tag "jquery.jscrollpane.min.js" %>
<%= javascript_include_tag "jquery.mousewheel.js"%>
<%= javascript_include_tag "mwheelintent.js" %>

<script type='text/javascript'>
$(function() {
	$('.bio').jScrollPane({showArrows: true});
});
	
</script>

app/views/artists/_tweet.html.erb
<script type='text/javascript'>
    $(document).ready(function(){
        $(".tweet").tweet({
            username: "<%= @artist.twitter_id %>",
            join_text: "auto",
            avatar_size: 32,
            count: 1,
            auto_join_text_default: "", 
            auto_join_text_ed: "",
            auto_join_text_ing: "",
            auto_join_text_reply: "",
            auto_join_text_url: "",
            loading_text: "loading tweets..."
        });
    });
</script>

<%= javascript_include_tag 'jquery.tweet.js' %>

app/views/artists/index.html.haml
%h2 Artists
.full-box
  .artists-wrapper
    %ul.artists
      - @artists.each do |artist|
        %li
          = link_to image_tag(artist.artist_home_img_url, 'data-hover' => artist.artist_home_img_hover_url), resource_path(artist)
          %h2.artist-name= link_to artist.name, artist_path(artist)
      %br.clear

app/views/artists/show.html.haml
- title "#{@artist.name} - The Bird Suit"
%h2= @artist.name
.two-third-box
  .wrapper.artist-main
    .bio-image= image_tag @artist.bio_pic_url, 'data-hover' => @artist.bio_pic_hover_url
    %h3.purple <span class="last_bold">Bio</span>graphy
    .bio
      = simple_format(@artist.biography_text)
    %br.clear
.one-third-box
  .wrapper
    = link_to image_tag(@artist.bio_video_img_url, 'data-hover' => @artist.bio_video_img_hover_url), video_artist_path(@artist), :rel => "#overlay", :remote => true
.one-third-box
  .wrapper
    .tweet
.full-box
  %h2 Release <strong>Material</strong>
  .wrapper
    \ <a class="prev browse left"></a> 
    .scrollable
      .items
        \ <div class="workgroup">
        - @artist.releases.each_with_index do |r, i|
          - if i % 3 == 0 && i != 0
            \ </div>
            \ <div class="workgroup"> 
            .item= link_to image_tag(r.release_img_url, 'data-hover' => r.release_img_hover_url), artist_release_path(@artist, r), :rel => "#overlay", :remote => true
          - else
            .item= link_to image_tag(r.release_img_url, 'data-hover' => r.release_img_hover_url), artist_release_path(@artist, r), :rel => "#overlay", :remote => true
        \ </div>
    \ <a class="next browse right"></a> 
    %br.clear
- content_for :javascripts do
  = render 'tweet'
  = render 'scrollbar'

app/views/artists/video.html.erb
<div id="video">
  <% if @artist.bio_video_type == "youtube" %>
    <iframe title="YouTube video player" width="600" height="368" src="http://www.youtube.com/embed/<%= @artist.bio_video_id %>" frameborder="0" allowfullscreen></iframe>
  <% end %>

  <% if @artist.bio_video_type == "vimeo" %>
    <div class="video">
      <iframe src="http://player.vimeo.com/video/<%= @artist.bio_video_id %>" width="600" height="368" frameborder="0"></iframe>
    </div>
  <%end%>
</div>