config/routes.rb
TheBirdsuit::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  
  resources :artists, :only => [:index, :show] do
    member do
      get 'video'
    end
    resources :releases, :only => [:show]
  end
  resources :posts, :only => [:index, :show]
  match 'blog' => 'posts#index', :as => :blog
  match 'promo' => 'pages#promo', :as => :promo
  match 'story' => 'pages#story', :as => :story
  match 'contact' => 'pages#contact', :as => :contact

end

app/views/pages/_tweet.html.erb
<script type='text/javascript'>
    $(document).ready(function(){
        $(".tweet").tweet({
            username: "TheBirdSuit",
            join_text: "auto",
            avatar_size: 32,
            count: 1,
            auto_join_text_default: "", 
            auto_join_text_ed: "",
            auto_join_text_ing: "",
            auto_join_text_reply: "",
            auto_join_text_url: "",
            loading_text: "loading tweets..."
        });
    });
</script>

<%= javascript_include_tag 'jquery.tweet.js' %>

app/views/pages/artists.html.haml
%h2 Matty Mayz
.two-third-box
  .wrapper
    .bio-image= image_tag 'http://placehold.it/220x280'
    %h3 Biography
    .bio
      %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam vulputate pulvinar justo vel sodales. Maecenas at justo quis felis faucibus tempus vitae non justo. Maecenas eu ligula libero, gravida pellentesque nisl. Fusce eget nisl nisi, a semper metus. 
      %p Vivamus orci augue, bibendum eu congue ut, congue condimentum tortor. Pellentesque viverra condimentum lectus at accumsan. Nam nec nunc nisi. Morbi laoreet nunc sit amet odio lobortis a varius odio facilisis. Vestibulum non neque eget mauris laoreet sodales. Etiam urna ligula, vehicula blandit rhoncus ac, elementum id neque.

      %p Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur id arcu nibh. Phasellus scelerisque tempus dui et interdum. Donec risus enim, elementum eget ultricies sit amet, scelerisque ac elit. Praesent eget semper elit. 
      %p Etiam porttitor, enim nec gravida aliquam, tortor orci cursus ipsum, ac cursus turpis urna sit amet mi. Donec vel tortor eget odio sollicitudin interdum nec eget mi. 
      %p Donec facilisis magna in dui blandit eu consectetur enim hendrerit. Donec sem ipsum, fringilla sit amet gravida ut, laoreet in arcu. In dolor leo, sodales commodo dignissim at, consectetur sed ipsum. Ut gravida convallis urna placerat ultricies. Curabitur eu nunc nisl. Nulla gravida commodo lacinia. Donec aliquet elit ac ligula pharetra eget sodales nisi dictum. 
      %p In gravida imperdiet porttitor.
    %br.clear
.one-third-box
  .wrapper
    = link_to image_tag('http://placehold.it/270x160'), story_path, :rel => "#overlay", :remote => true
.one-third-box
  .wrapper
    = image_tag 'http://placehold.it/270x56'
.full-box
  %h2 Release <strong>Material</strong>
  .wrapper
    \ <a class="prev browse left"></a> 
    .scrollable
      .items
        .work-group
          .item= link_to image_tag('http://placehold.it/270x160'), story_path, :rel => "#overlay", :remote => true
          .item= link_to image_tag('http://placehold.it/270x160'), story_path, :rel => "#overlay", :remote => true
          .item= link_to image_tag('http://placehold.it/270x160'), story_path, :rel => "#overlay", :remote => true
        .work-group
          = link_to image_tag('http://placehold.it/270x160'), story_path, :rel => "#overlay", :remote => true
          = link_to image_tag('http://placehold.it/270x160'), story_path, :rel => "#overlay", :remote => true
          = link_to image_tag('http://placehold.it/270x160'), story_path, :rel => "#overlay", :remote => true
    \ <a class="next browse right"></a> 
    %br.clear
       

app/views/pages/blog.html.haml
%h2 Latest <strong>News</strong>
.wrapper
%h2 Crowd <strong>Control</strong>
.wrapper
-content_for :sidebar do
  .wrapper
    Twitter
  %h2 Latest <strong>Release</strong>
  .wrapper
    = image_tag 'http://placehold.it/270x150'
  %h2 We <strong>Are</strong> The Bird Suit
  .wrapper
    = image_tag 'http://placehold.it/270x100'
    = image_tag 'http://placehold.it/270x100'
    = image_tag 'http://placehold.it/270x100'
    = image_tag 'http://placehold.it/270x100'
    = image_tag 'http://placehold.it/270x100'
    = image_tag 'http://placehold.it/270x100'
  %h2 Arch<strong>ive</strong>
  .wrapper
    = image_tag 'http://placehold.it/270x150'    

app/views/pages/contact.html.haml
- title "Contact Us - The Bird Suit"
%h2= @page.title
.wrapper
  =image_tag @page.page_img_url
  = @page.body.html_safe

app/views/pages/home.html.haml
.two-third-box
  %h2 Featured <strong>News</strong>
  -#
    .wrapper.featured{:style => "background:url('#{@featured.featured_img_url}')"}
      .featured-text
        %h3= link_to @featured.title, post_path(@featured)
        %p= @featured.summary
  .wrapper
    .featured2
      = link_to image_tag(@featured.featured_img_url), post_path(@featured)
      .featured2-text
        %h3= link_to @featured.title, post_path(@featured)
        %small== By "#{@featured.author}" | #{@featured.published_date.strftime('%B %d, %Y')}
        %p
          = @featured.summary
          = link_to "Read More", post_path(@featured), :class => "a-btn"
.one-third-box
  %h2 Latest Release
  .wrapper
    =link_to image_tag(@release.release_img_url, 'data-hover' => @release.release_img_hover_url), artist_release_path(@release.artist_id, @release), :rel => "#overlay", :remote => true
.one-third-box
  .wrapper.small-tweet
    .tweet
.full-box
  %h2 Artist <strong>Roster</strong>
  .artists-wrapper
    %ul.artists
      - @artists.each do |artist|
        %li
          = link_to image_tag(artist.artist_home_img_url, 'data-hover' => artist.artist_home_img_hover_url), artist_path(artist)
          %h2.artist-name= link_to artist.name, artist_path(artist)
    %br.clear

            
-content_for :javascripts do
  = render 'tweet'

app/views/pages/promo.html.haml
%h1= @page.title
= @page.body.html_safe

%h1= link_to "Enter", root_path

app/views/pages/story.html.haml
- title "Story - The Bird Suit"
%h2 We Are <strong>The Bird Suit</strong>
.wrapper
  .title-img= image_tag @page.page_img_url
  .two-third-box
    %h2= @page.title
    .bodyContent= @page.body.html_safe
  .story-sidebar
    %h2 Artists

    - @artists.each do |artist| 
      = link_to image_tag(artist.roster_pic_url, 'data-hover' => artist.roster_pic_hover_url), artist_path(artist)

  %br.clear