config/routes.rb
TheBirdsuit::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  
  resources :artists, :only => [:index, :show] do
    member do
      get 'video'
    end
    resources :releases, :only => [:show]
  end
  resources :posts, :only => [:index, :show]
  match 'blog' => 'posts#index', :as => :blog
  match 'promo' => 'pages#promo', :as => :promo
  match 'story' => 'pages#story', :as => :story
  match 'contact' => 'pages#contact', :as => :contact

end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22601717-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_fb_include.html.erb
<div id="fb-root"></div>
    <script>
      window.fbAsyncInit = function() {
        FB.init({appId: '216783115006036', status: true, cookie: true,
                 xfbml: true});
      };
      (function() {
        var e = document.createElement('script');
        e.type = 'text/javascript';
        e.src = document.location.protocol +
          '//connect.facebook.net/en_US/all.js';
        e.async = true;
        document.getElementById('fb-root').appendChild(e);
      }());
    </script>

app/views/layouts/_footer.html.haml
.footerWrap
  .footer-links== #{link_to "Home", root_path} | #{link_to "Story", story_path} | #{link_to "Artists", artists_path} |#{link_to "Blog", blog_path} | #{link_to "Contact", contact_path}
  == &copy; #{Date.today.strftime('%Y')} The Bird Suit
.footer-credits
  == Design by #{link_to "CHINGEL", 'http://chingel.com'}
  %br
  Developed by
  = link_to "Kurios Creative Design", "http://kurioscreative.com"

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/
%meta{ :content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible" }/

%title
  = content_for?(:title) ? content_for(:title) : "The Bird Suit"
  
%meta{ :content => "An artist collective focusing on electronic music, visual arts, and the noise/lifestyle that comes with it.", :name => "description" }/
%meta{ :content => "The Bird Suit", :name => "author" }/
%meta{ :content => "electronic, dance, music, blog, visual arts, management, press", :name => "keywords"}

%meta{ :property => "og:site_name", :content => "The Bird Suit" }
%meta{ :property => "fb:app_id", :content => "216783115006036"}

= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Arimo:regular,italic,bold'
-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :content => "width=device-width, initial-scale=1.0", :name => "viewport" }/


= render :partial => 'layouts/stylesheets'

-# JavaScript at the bottom

= csrf_meta_tag
= render :partial => 'layouts/analytics'

= yield(:head)

app/views/layouts/_header.html.haml
.headerWrap
  .header
    = render 'layouts/mailchimp'
    %h1= link_to image_tag('logo.png', :alt => "The Bird Suit", :height => 53, :width => 351), root_path
    %nav
      %ul.nav
        %li= link_to "Home", root_path
        %li= link_to "Story", story_path
        %li{:id => "artist-link"}
          = link_to "Artists", artists_path
          %ul.sub-nav
            - if @artists
              - @artists.each do |artist| 
                %li=link_to artist.name, artist_path(artist)
            - else
              - Artist.all.each do |artist| 
                %li=link_to artist.name, artist_path(artist)
        %li= link_to "Blog", blog_path
        %li= link_to "Contact", contact_path
        = link_to image_tag('link_fb.gif', :alt => "Find The Bird Suit on Facebook", 'data-hover' => './images/link_fb_hover.gif'), "http://www.facebook.com/TheBirdSuit"
        = link_to image_tag('link_twitter.gif', :alt => "Find The Bird Suit on Twitter", 'data-hover' => './images/link_twitter_hover.gif') , "http://twitter.com/TheBirdSuit"
    %br{:style => "clear:both"}

app/views/layouts/_javascripts.html.haml
= javascript_include_tag :defaults

= yield(:javascripts)

app/views/layouts/_mailchimp.html.erb
<!-- Begin MailChimp Signup Form -->
<script type="text/javascript">
// delete this script tag and use a "div.mce_inline_error{ XXX !important}" selector
// or fill this in and it will be inlined when errors are generated
var mc_custom_error_style = '';
</script>

<div id="mc_embed_signup">
  JOIN THE BIRD SUIT MAILING LIST
<form action="http://thebirdsuit.us2.list-manage1.com/subscribe/post?u=610a74eab0d62951c17785bdf&amp;id=84d7eba128" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
	<fieldset>
<div class="mc-field-group">
<input type="text" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Your Email">
</div>
		<div id="mce-responses">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>
		<div><input type="submit" value="JOIN" name="subscribe" id="mc-embedded-subscribe" class="btn"></div>
	</fieldset>	
</form>
</div>

<!--End mc_embed_signup-->

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/print.css', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
/[if lt IE 9]
  = javascript_include_tag 'http://html5shiv.googlecode.com/svn/trunk/html5.js'  

app/views/layouts/application.html.haml
!!! 5

%head
  = render :partial => 'layouts/head'
%body{ :lang => 'en', :class => "bp one-col #{controller.controller_name}" }
  %header
    = render :partial => 'layouts/header'
  #container
    #overlay.apple_overlay
      .contentWrap
    #content
      = render :partial => 'layouts/flashes'
      #breadcrumbs= crumbs
      = yield
  %footer
    = render :partial => 'layouts/footer'
    = render :partial => 'layouts/javascripts'

app/views/layouts/blog.html.haml
!!! 5

= render :partial => 'layouts/head'
%body{ :lang => 'en', :class => "bp two-col #{controller.controller_name}" }
  %header
    = render :partial => 'layouts/header'
  #container  
    #content
      = render :partial => 'layouts/flashes'
      #breadcrumbs= crumbs
      = yield
    #sidebar
      =yield(:sidebar)
  %footer
    .footer
      = render :partial => 'layouts/footer'
    = render :partial => 'layouts/javascripts'

app/views/layouts/posts.html.haml
!!! 5

%head
  = render :partial => 'layouts/head'
%body{ :lang => 'en', :class => "bp two-col #{controller.controller_name}" }
  %header
    = render :partial => 'layouts/header'
  #container
    #overlay.apple_overlay
      .contentWrap
    #content
      = render :partial => 'layouts/flashes'
      #breadcrumbs= crumbs
      = yield
    #sidebar
      = yield(:sidebar)

  %footer
    = render :partial => 'layouts/footer'
    = render :partial => 'layouts/javascripts'
    = render 'layouts/fb_include'

app/views/layouts/splash.html.haml
!!! 5

= render :partial => 'layouts/head'
%body{ :lang => 'en', :class => "bp one-col splash #{controller.controller_name}" }
  %header
  #container
    #content
      = render :partial => 'layouts/flashes'
      = yield
  %footer